{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorflow\\python\\framework\\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint8 = np.dtype([(\"qint8\", np.int8, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint8 = np.dtype([(\"quint8\", np.uint8, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint16 = np.dtype([(\"qint16\", np.int16, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_quint16 = np.dtype([(\"quint16\", np.uint16, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  _np_qint32 = np.dtype([(\"qint32\", np.int32, 1)])\n",
      "C:\\Users\\munu2\\anaconda3\\lib\\site-packages\\tensorboard\\compat\\tensorflow_stub\\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.\n",
      "  np_resource = np.dtype([(\"resource\", np.ubyte, 1)])\n"
     ]
    }
   ],
   "source": [
    "from __future__ import print_function\n",
    "\n",
    "import math\n",
    "\n",
    "from IPython import display\n",
    "from matplotlib import cm\n",
    "from matplotlib import gridspec\n",
    "from matplotlib import pyplot as plt\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from sklearn import metrics\n",
    "import tensorflow as tf\n",
    "from tensorflow.python.data import Dataset\n",
    "\n",
    "tf.logging.set_verbosity(tf.logging.ERROR)\n",
    "pd.options.display.max_rows = 10\n",
    "pd.options.display.float_format = '{:.1f}'.format\n",
    "\n",
    "california_housing_dataframe = pd.read_csv(\"https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv\", sep=\",\")\n",
    "\n",
    "california_housing_dataframe = california_housing_dataframe.reindex(\n",
    "    np.random.permutation(california_housing_dataframe.index))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def preprocess_features(california_housing_dataframe):\n",
    "  \"\"\"Prepares input features from California housing data set.\n",
    "\n",
    "  Args:\n",
    "    california_housing_dataframe: A Pandas DataFrame expected to contain data\n",
    "      from the California housing data set.\n",
    "  Returns:\n",
    "    A DataFrame that contains the features to be used for the model, including\n",
    "    synthetic features.\n",
    "  \"\"\"\n",
    "  selected_features = california_housing_dataframe[\n",
    "    [\"latitude\",\n",
    "     \"longitude\",\n",
    "     \"housing_median_age\",\n",
    "     \"total_rooms\",\n",
    "     \"total_bedrooms\",\n",
    "     \"population\",\n",
    "     \"households\",\n",
    "     \"median_income\"]]\n",
    "  processed_features = selected_features.copy()\n",
    "  # Create a synthetic feature.\n",
    "  processed_features[\"rooms_per_person\"] = (\n",
    "    california_housing_dataframe[\"total_rooms\"] /\n",
    "    california_housing_dataframe[\"population\"])\n",
    "  return processed_features\n",
    "\n",
    "def preprocess_targets(california_housing_dataframe):\n",
    "  \"\"\"Prepares target features (i.e., labels) from California housing data set.\n",
    "\n",
    "  Args:\n",
    "    california_housing_dataframe: A Pandas DataFrame expected to contain data\n",
    "      from the California housing data set.\n",
    "  Returns:\n",
    "    A DataFrame that contains the target feature.\n",
    "  \"\"\"\n",
    "  output_targets = pd.DataFrame()\n",
    "  # Scale the target to be in units of thousands of dollars.\n",
    "  output_targets[\"median_house_value\"] = (\n",
    "    california_housing_dataframe[\"median_house_value\"] / 1000.0)\n",
    "  return output_targets"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Training examples summary:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>housing_median_age</th>\n",
       "      <th>total_rooms</th>\n",
       "      <th>total_bedrooms</th>\n",
       "      <th>population</th>\n",
       "      <th>households</th>\n",
       "      <th>median_income</th>\n",
       "      <th>rooms_per_person</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "      <td>12000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>35.6</td>\n",
       "      <td>-119.5</td>\n",
       "      <td>28.6</td>\n",
       "      <td>2644.6</td>\n",
       "      <td>539.6</td>\n",
       "      <td>1427.8</td>\n",
       "      <td>501.3</td>\n",
       "      <td>3.9</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>2.1</td>\n",
       "      <td>2.0</td>\n",
       "      <td>12.5</td>\n",
       "      <td>2217.3</td>\n",
       "      <td>429.3</td>\n",
       "      <td>1177.2</td>\n",
       "      <td>391.6</td>\n",
       "      <td>1.9</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>32.5</td>\n",
       "      <td>-124.3</td>\n",
       "      <td>1.0</td>\n",
       "      <td>8.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>33.9</td>\n",
       "      <td>-121.8</td>\n",
       "      <td>18.0</td>\n",
       "      <td>1453.0</td>\n",
       "      <td>296.0</td>\n",
       "      <td>786.0</td>\n",
       "      <td>281.0</td>\n",
       "      <td>2.6</td>\n",
       "      <td>1.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>34.2</td>\n",
       "      <td>-118.5</td>\n",
       "      <td>29.0</td>\n",
       "      <td>2122.0</td>\n",
       "      <td>433.0</td>\n",
       "      <td>1163.0</td>\n",
       "      <td>408.0</td>\n",
       "      <td>3.5</td>\n",
       "      <td>1.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>37.7</td>\n",
       "      <td>-118.0</td>\n",
       "      <td>37.0</td>\n",
       "      <td>3148.0</td>\n",
       "      <td>646.0</td>\n",
       "      <td>1720.2</td>\n",
       "      <td>603.0</td>\n",
       "      <td>4.8</td>\n",
       "      <td>2.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>42.0</td>\n",
       "      <td>-114.3</td>\n",
       "      <td>52.0</td>\n",
       "      <td>37937.0</td>\n",
       "      <td>6445.0</td>\n",
       "      <td>35682.0</td>\n",
       "      <td>6082.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>41.3</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \\\n",
       "count   12000.0    12000.0             12000.0      12000.0         12000.0   \n",
       "mean       35.6     -119.5                28.6       2644.6           539.6   \n",
       "std         2.1        2.0                12.5       2217.3           429.3   \n",
       "min        32.5     -124.3                 1.0          8.0             1.0   \n",
       "25%        33.9     -121.8                18.0       1453.0           296.0   \n",
       "50%        34.2     -118.5                29.0       2122.0           433.0   \n",
       "75%        37.7     -118.0                37.0       3148.0           646.0   \n",
       "max        42.0     -114.3                52.0      37937.0          6445.0   \n",
       "\n",
       "       population  households  median_income  rooms_per_person  \n",
       "count     12000.0     12000.0        12000.0           12000.0  \n",
       "mean       1427.8       501.3            3.9               2.0  \n",
       "std        1177.2       391.6            1.9               1.0  \n",
       "min           3.0         1.0            0.5               0.0  \n",
       "25%         786.0       281.0            2.6               1.5  \n",
       "50%        1163.0       408.0            3.5               1.9  \n",
       "75%        1720.2       603.0            4.8               2.3  \n",
       "max       35682.0      6082.0           15.0              41.3  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Validation examples summary:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>latitude</th>\n",
       "      <th>longitude</th>\n",
       "      <th>housing_median_age</th>\n",
       "      <th>total_rooms</th>\n",
       "      <th>total_bedrooms</th>\n",
       "      <th>population</th>\n",
       "      <th>households</th>\n",
       "      <th>median_income</th>\n",
       "      <th>rooms_per_person</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "      <td>5000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>35.6</td>\n",
       "      <td>-119.6</td>\n",
       "      <td>28.6</td>\n",
       "      <td>2641.3</td>\n",
       "      <td>538.8</td>\n",
       "      <td>1433.8</td>\n",
       "      <td>501.1</td>\n",
       "      <td>3.9</td>\n",
       "      <td>2.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>2.1</td>\n",
       "      <td>2.0</td>\n",
       "      <td>12.8</td>\n",
       "      <td>2087.9</td>\n",
       "      <td>402.1</td>\n",
       "      <td>1074.2</td>\n",
       "      <td>367.0</td>\n",
       "      <td>1.9</td>\n",
       "      <td>1.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>32.5</td>\n",
       "      <td>-124.3</td>\n",
       "      <td>1.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>0.5</td>\n",
       "      <td>0.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>33.9</td>\n",
       "      <td>-121.8</td>\n",
       "      <td>18.0</td>\n",
       "      <td>1474.8</td>\n",
       "      <td>298.0</td>\n",
       "      <td>797.8</td>\n",
       "      <td>283.0</td>\n",
       "      <td>2.6</td>\n",
       "      <td>1.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>34.3</td>\n",
       "      <td>-118.5</td>\n",
       "      <td>29.0</td>\n",
       "      <td>2150.0</td>\n",
       "      <td>435.0</td>\n",
       "      <td>1178.5</td>\n",
       "      <td>410.0</td>\n",
       "      <td>3.6</td>\n",
       "      <td>1.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>37.7</td>\n",
       "      <td>-118.0</td>\n",
       "      <td>37.0</td>\n",
       "      <td>3156.2</td>\n",
       "      <td>655.2</td>\n",
       "      <td>1722.0</td>\n",
       "      <td>610.0</td>\n",
       "      <td>4.8</td>\n",
       "      <td>2.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>41.9</td>\n",
       "      <td>-114.6</td>\n",
       "      <td>52.0</td>\n",
       "      <td>28258.0</td>\n",
       "      <td>4335.0</td>\n",
       "      <td>12203.0</td>\n",
       "      <td>3933.0</td>\n",
       "      <td>15.0</td>\n",
       "      <td>55.2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       latitude  longitude  housing_median_age  total_rooms  total_bedrooms  \\\n",
       "count    5000.0     5000.0              5000.0       5000.0          5000.0   \n",
       "mean       35.6     -119.6                28.6       2641.3           538.8   \n",
       "std         2.1        2.0                12.8       2087.9           402.1   \n",
       "min        32.5     -124.3                 1.0          2.0             2.0   \n",
       "25%        33.9     -121.8                18.0       1474.8           298.0   \n",
       "50%        34.3     -118.5                29.0       2150.0           435.0   \n",
       "75%        37.7     -118.0                37.0       3156.2           655.2   \n",
       "max        41.9     -114.6                52.0      28258.0          4335.0   \n",
       "\n",
       "       population  households  median_income  rooms_per_person  \n",
       "count      5000.0      5000.0         5000.0            5000.0  \n",
       "mean       1433.8       501.1            3.9               2.0  \n",
       "std        1074.2       367.0            1.9               1.4  \n",
       "min           6.0         2.0            0.5               0.1  \n",
       "25%         797.8       283.0            2.6               1.5  \n",
       "50%        1178.5       410.0            3.6               1.9  \n",
       "75%        1722.0       610.0            4.8               2.3  \n",
       "max       12203.0      3933.0           15.0              55.2  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Training targets summary:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>median_house_value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>12000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>207.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>116.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>15.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>118.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>179.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>264.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>500.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       median_house_value\n",
       "count             12000.0\n",
       "mean                207.1\n",
       "std                 116.3\n",
       "min                  15.0\n",
       "25%                 118.8\n",
       "50%                 179.9\n",
       "75%                 264.7\n",
       "max                 500.0"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Validation targets summary:\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>median_house_value</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>5000.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>207.8</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>115.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>15.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>121.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>181.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>265.7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>500.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "       median_house_value\n",
       "count              5000.0\n",
       "mean                207.8\n",
       "std                 115.3\n",
       "min                  15.0\n",
       "25%                 121.4\n",
       "50%                 181.5\n",
       "75%                 265.7\n",
       "max                 500.0"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# Choose the first 12000 (out of 17000) examples for training.\n",
    "training_examples = preprocess_features(california_housing_dataframe.head(12000))\n",
    "training_targets = preprocess_targets(california_housing_dataframe.head(12000))\n",
    "\n",
    "# Choose the last 5000 (out of 17000) examples for validation.\n",
    "validation_examples = preprocess_features(california_housing_dataframe.tail(5000))\n",
    "validation_targets = preprocess_targets(california_housing_dataframe.tail(5000))\n",
    "\n",
    "# Double-check that we've done the right thing.\n",
    "print(\"Training examples summary:\")\n",
    "display.display(training_examples.describe())\n",
    "print(\"Validation examples summary:\")\n",
    "display.display(validation_examples.describe())\n",
    "\n",
    "print(\"Training targets summary:\")\n",
    "display.display(training_targets.describe())\n",
    "print(\"Validation targets summary:\")\n",
    "display.display(validation_targets.describe())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def construct_feature_columns(input_features):\n",
    "    return set([tf.feature_column.numeric_column(my_feature) for my_feature in input_features])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "def my_input_fn(features, targets, batch_size=1, shuffle=True, num_epochs=None):\n",
    "    \"\"\"Trains a neural net regression model.\n",
    "  \n",
    "    Args:\n",
    "      features: pandas DataFrame of features\n",
    "      targets: pandas DataFrame of targets\n",
    "      batch_size: Size of batches to be passed to the model\n",
    "      shuffle: True or False. Whether to shuffle the data.\n",
    "      num_epochs: Number of epochs for which data should be repeated. None = repeat indefinitely\n",
    "    Returns:\n",
    "      Tuple of (features, labels) for next data batch\n",
    "    \"\"\"\n",
    "    features = {key:np.array(value) for key, value in dict(features).items()}\n",
    "    \n",
    "    ds = Dataset.from_tensor_slices((features, targets))\n",
    "    ds = ds.batch(batch_size).repeat(num_epochs)\n",
    "    \n",
    "    if shuffle:\n",
    "        ds = ds.shuffle(10000)\n",
    "    \n",
    "    features, labels = ds.make_one_shot_iterator().get_next()\n",
    "    return features, labels"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_nn_regression_model(\n",
    "    learning_rate, steps, batch_size, hidden_units, training_examples, training_targets, validation_examples, validation_targets):\n",
    "    \n",
    "    periods = 10\n",
    "    steps_per_period = steps / periods\n",
    "    \n",
    "    mOptimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate) # optimizer 및 학습률 설정\n",
    "    mOptimizer = tf.contrib.estimator.clip_gradients_by_norm(mOptimizer, 5.0)\n",
    "    \n",
    "    dnn_regressor = tf.estimator.DNNRegressor(\n",
    "        feature_columns = construct_feature_columns(training_examples),\n",
    "        hidden_units = hidden_units,\n",
    "        optimizer = mOptimizer\n",
    "    )\n",
    "    \n",
    "    training_input_fn = lambda: my_input_fn(training_examples,\n",
    "                                           training_targets[\"median_house_value\"],\n",
    "                                           batch_size = batch_size)\n",
    "    \n",
    "    predict_training_input_fn = lambda: my_input_fn(training_examples,\n",
    "                                           training_targets[\"median_house_value\"],\n",
    "                                            num_epochs=1, shuffle=False)\n",
    "    \n",
    "    predict_validation_input_fn = lambda: my_input_fn(validation_examples,\n",
    "                                           validation_targets[\"median_house_value\"],\n",
    "                                           num_epochs=1, shuffle=False)\n",
    "    training_rmse = []\n",
    "    validation_rmse = []\n",
    "    \n",
    "    for period in range(0, periods):\n",
    "        dnn_regressor.train(\n",
    "            input_fn = training_input_fn,\n",
    "            steps = steps_per_period\n",
    "        )\n",
    "    \n",
    "         # Take a break and compute predictions.\n",
    "        training_predictions = dnn_regressor.predict(input_fn=predict_training_input_fn)\n",
    "        training_predictions = np.array([item['predictions'][0] for item in training_predictions])\n",
    "    \n",
    "        validation_predictions = dnn_regressor.predict(input_fn=predict_validation_input_fn)\n",
    "        validation_predictions = np.array([item['predictions'][0] for item in validation_predictions])\n",
    "        \n",
    "        # Compute training and validation loss.\n",
    "        training_root_mean_squared_error = math.sqrt(\n",
    "            metrics.mean_squared_error(training_predictions, training_targets))\n",
    "        validation_root_mean_squared_error = math.sqrt(\n",
    "            metrics.mean_squared_error(validation_predictions, validation_targets))\n",
    "        \n",
    "        # Occasionally print the current loss.\n",
    "        print(\"  period %02d : %0.2f\" % (period, training_root_mean_squared_error))\n",
    "        # Add the loss metrics from this period to our list.\n",
    "        training_rmse.append(training_root_mean_squared_error)\n",
    "        validation_rmse.append(validation_root_mean_squared_error)\n",
    " \n",
    "\n",
    "      # Output a graph of loss metrics over periods.\n",
    "    plt.ylabel(\"RMSE\")\n",
    "    plt.xlabel(\"Periods\")\n",
    "    plt.title(\"Root Mean Squared Error vs. Periods\")\n",
    "    plt.tight_layout()\n",
    "    plt.plot(training_rmse, label=\"training\")\n",
    "    plt.plot(validation_rmse, label=\"validation\")\n",
    "    plt.legend()\n",
    "\n",
    "    print(\"Final RMSE (on training data):   %0.2f\" % training_root_mean_squared_error)\n",
    "    print(\"Final RMSE (on validation data): %0.2f\" % validation_root_mean_squared_error)\n",
    "\n",
    "    return dnn_regressor"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61BBB69C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61BBB69C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DF0D988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DF0D988>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B3208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B3208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B33C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B33C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C144648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C144648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B34C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6187B34C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD81B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD81B88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA998C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA998C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E03A1C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E03A1C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342DC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342DC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342A48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342A48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342348>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342348>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C342B48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D9F1608>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D9F1608>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6185AC088>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6185AC088>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DFB5888>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DFB5888>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616A05C48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616A05C48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616A05588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616A05588>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C613E36288>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C613E36288>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BEA4408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BEA4408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3188>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3188>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 00 : 535.43\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61BEB7A48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61BEB7A48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61698E208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61698E208>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75EDC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75EDC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E6C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E6C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75EF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75EF88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D712E88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D712E88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DF228C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DF228C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61F4E4688>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61F4E4688>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780388>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780388>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780D48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780D48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BE91808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BE91808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780248>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618780248>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F52FBC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F52FBC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615414E48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615414E48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C614D3CEC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C614D3CEC8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D8AC408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D8AC408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D8AC0C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D8AC0C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C54E988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C54E988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C54ECC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C54ECC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615397D48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615397D48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 01 : 475.39\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DCE3D48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DCE3D48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DD9F6C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DD9F6C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3E48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3E48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3CC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3CC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3E08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3E08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3548>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6186E3548>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61869C188>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61869C188>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615905208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615905208>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DC34248>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DC34248>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DAB0B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DAB0B48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DC34EC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DC34EC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61E252808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61E252808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DC34FC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DC34FC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BAB1348>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BAB1348>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DC96708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DC96708>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BF1B648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BF1B648>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826A88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826EC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618826EC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618602388>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618602388>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4C3A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4C3A88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 02 : 303.33\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61D7B0648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61D7B0648>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61D9E63C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61D9E63C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD9508>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD9508>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD98C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD98C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD9D88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BFD9D88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D919808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D919808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD605C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD605C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61F563BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61F563BC8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BE1C248>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BE1C248>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81DC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81DC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB81408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615803188>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615803188>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D75E908>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C618944A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C618944A88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E05CAC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E05CAC8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C180B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C180B48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181D5B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181D5B48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61881E1C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61881E1C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181D5308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181D5308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616B576C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616B576C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 03 : 177.03\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA73A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA73A08>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BF26208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BF26208>>: AttributeError: module 'gast' has no attribute 'Num'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158CF488>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158CF488>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158CFF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158CFF88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C382988>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C382988>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BF26148>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BF26148>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BC6AC48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BC6AC48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C618802688>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C618802688>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61161E608>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61161E608>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618438088>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618438088>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618207B08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618207B08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DCD5A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DCD5A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618207BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618207BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BEBEF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BEBEF88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61705E608>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61705E608>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61705EA48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61705EA48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5ACE48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5ACE48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5AC408>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5AC408>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5AC848>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5AC848>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB38708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB38708>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616E36948>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616E36948>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 04 : 325.02\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61C463708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61C463708>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C615397A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C615397A88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B8348>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B8348>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B89C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B89C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616ED2F88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616ED2F88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B8EC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5B8EC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BA76508>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BA76508>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DFC4208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DFC4208>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BED58C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BED58C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBC9E48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBC9E48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBC9688>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBC9688>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C070748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C070748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0704C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0704C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61698EF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61698EF88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C616999B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C616999B88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C6185A1B88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C6185A1B88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97188>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97188>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97C88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97C88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C1F5148>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C1F5148>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97E88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616D97E88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5E6348>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5E6348>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 05 : 384.83\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61E1F4D88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61E1F4D88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DFD9D48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DFD9D48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C149308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C149308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C149708>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C149708>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F590C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F590C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61B979B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61B979B48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BAB6308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BAB6308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61C16EF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61C16EF88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C616F12F88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C616F12F88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616F18CC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616F18CC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9E48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9E48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9048>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9A08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C0A9A08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C50AD88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C50AD88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61D9E9B48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61D9E9B48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61B92A048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61B92A048>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDC388>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDC388>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDCE48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDCE48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDCE88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDCE88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDC548>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BCDC548>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616963448>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C616963448>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 06 : 432.70\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DD8BE48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DD8BE48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C614F17FC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C614F17FC8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD855C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD855C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD85BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD85BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181E3D48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6181E3D48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD856C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DD856C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615876208>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615876208>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615419948>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C615419948>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61F4EA948>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61F4EA948>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA248>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA248>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F5501C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F5501C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA7C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61F4EA7C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D90B2C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D90B2C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61B98F748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61B98F748>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E24E848>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61E24E848>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEEA08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEEA08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEEA88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEEA88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEE108>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEE108>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEE0C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BBEE0C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6183CCF88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6183CCF88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 07 : 168.23\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61694AC48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61694AC48>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BBEE548>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BBEE548>>: AttributeError: module 'gast' has no attribute 'Num'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165908>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165608>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165608>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165648>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C165648>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61581F7C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61581F7C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA9E488>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61DA9E488>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61C24AD88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61C24AD88>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24A788>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24A788>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24AB08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24AB08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615684C08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C615684C08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24A6C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C24A6C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB2A308>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BB2A308>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6185BA608>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6185BA608>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DEB7908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61DEB7908>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C000548>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C000548>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D7C3808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D7C3808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C605808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C605808>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DBCECC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DBCECC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D886F88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D886F88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 08 : 159.62\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61E171F08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C61E171F08>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BD06808>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61BD06808>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C614CCE4C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C614CCE4C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06788>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06788>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06848>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06848>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06DC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BD06DC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D9031C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61D9031C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C614D34048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C614D34048>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61B96C5C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61B96C5C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE809C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE809C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE80E08>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE80E08>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BA0D748>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BA0D748>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE805C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61DE805C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BC9C9C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61BC9C9C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING: Entity <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6169A6548>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method _DNNModel.call of <tensorflow_estimator.python.estimator.canned.dnn._DNNModel object at 0x000002C6169A6548>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61873F0C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DenseFeatures.call of <tensorflow.python.feature_column.feature_column_v2.DenseFeatures object at 0x000002C61873F0C8>>: AttributeError: module 'gast' has no attribute 'Num'\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5490C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5490C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158E49C8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158E49C8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158E4A88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C6158E4A88>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5E4BC8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C61C5E4BC8>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "WARNING: Entity <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618571E48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Dense.call of <tensorflow.python.layers.core.Dense object at 0x000002C618571E48>>: AssertionError: Bad argument number for Name: 3, expecting 4\n",
      "  period 09 : 183.62\n",
      "Final RMSE (on training data):   183.62\n",
      "Final RMSE (on validation data): 183.36\n"
     ]
    },
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAaMAAAEYCAYAAADxmJlCAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4xLjMsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+AADFEAAAgAElEQVR4nOzdd3hUZfbA8e9JJySEEFoghEBC75CEKFKDCqKCqIhgQQEVda27q26zrLq7rqv+XAWlCKIUEVZsgKiASCe0EHrooYTQQiCkv78/7gVDSAMymWRyPs8zT2bufe+dM8lkzrz3nvu+YoxBKaWUciY3ZweglFJKaTJSSinldJqMlFJKOZ0mI6WUUk6nyUgppZTTaTJSSinldJqMlKokRMSISISz46jMRORPIjLxKredIiKvl3VMyqLJyMWJyD4ROS8iZ0XkqP0P5VcG+w2zPxw9imnzit3mqQLLn7GXv3KtcVwpEblBRFaISKqInBSR5SISVd5xlDURWSIiGfbf+cLtW2fHVRbs98o5+zUdEpF3RMT9avZljHnTGDOqrGNU106TUdVwmzHGD+gIdAJeKsfn3gk8WGDZA/byciUiNYDvgP8CtYCGwKtAphNiuaoP0xI8aYzxy3e7rYjnvuwLRHFfKkq7DwfrYL+HY4FhwOgr3YETYlZXQJNRFWKMOQr8gJWUABCRABGZKiIpIrJfRP4iIm72Ojf78X4ROWa3C7A3XWr/PG1/Y72uiKddC/iKSBt7n22Aavbyi0TkVhHZKCKn7Z5L+3zrXhSR3SKSJiJbReSOfOtGiMgyEXlbRE6JyF4R6V9ELM3t38MMY0yuMea8MWahMSbe3pe7vZ/jIrJHRJ7I3/uze5l98z33KyLyeb7HX9q9z1QRWXrhNdvrpojIOBGZJyLngN4i4m0/3wERSRaRj0SkWr5t/iAiR0TksIg8XMRrKpGI9BKRJBF5QUSOApMLW2a3HS0iiXav8RsRaZBvP8b+newCdhXyPAtE5MkCyzaJyGCxvGu/j1JFJF5E2l7pazHGbAd+Bdra+28gInPs9+/e/L1w++8zW0Q+F5EzwIhC/ma3i8gW+323RERa5VvXSUTW2++7LwCffOtqi8h39nYnReTXC/836uroL68KEZEQoD+QmG/xf4EAoCnQE6vX8pC9boR9622v9wM+sNf1sH/WtL+FryzmqT+z9wtWL2lqgbg6A58AjwJBwMfANyLibTfZDXS343wV+FxEgvPtoiuwA6gNvAVMEhEpJI6dQK6IfCoi/UUksMD60cCtWL3HSOCuYl5TYeYDzYC6wHpgWoH1w4A3AH9gGfAvrATZEYjA6qn9DUBE+gG/B26099mXa1MfqzfYGHiksGUi0gf4BzAECAb2AzML7GcQ1u+7dSHPMR2498IDEWlt7/t74Cas90xzoCZwD3DiSl+Evc/uwAb7w/9bYBPW7y4WeEZEbs63yUBgtv2c0wrsqzkwA3gGqAPMA74VES8R8QLmYr13awFfAnfm2/x5IMnerh7wJ0DHVrsWxhi9ufAN2AecBdKw/ll+xkogAO5Yh6ha52v/KLDEvv8z8Hi+dS2AbMADCLP351HMc78CfA6EAgcAT/tnI3v5K3a7ccDfC2y7A+hZxH43AgPt+yOAxHzrfO246hexbStgCtYHSQ7wDVDPXrcIeCxf25vyv0b7d9m34Osr4nlq2tsG2I+nAFPzrRfgHBCeb9l1wF77/ifAP/Ota27vL6KI51sCpAOn893+bq/rBWQBPvnaF7ZsEvBWvsd+9t87zH5sgD7F/L397dfU2H78BvCJfb8P1peBGMDtCt/DBjgDnML6YvI61hfprsCBAm1fAibn+/ssLew9ad//KzAr3zo34JD9u+kBHAYk3/oVwOv2/deAr4v6e+jtym/aM6oaBhlj/LH+yVpi9SCwf3phfQO+YD/Wt0yABoWs88D6JlhqxpgDWL2xN4FdxpiDBZo0Bp63D3mcFpHTWAmrAYCIPJDvEN5prEM0tfNtfzTfc6Xbdwst0jDGbDPGjDDGhNj7aQC8l+/15o9tf8Hti2If4vunfTjxDFbiokCc+fddBytxrsv3uhbYy682lqeMMTXz3f6ab12KMSajQPuCyy75extjzmL1Xhrma1Pwb3eRMSYNqxc01F40FLs3YoxZhNWr/hBIFpHxYp3DK63OxphAY0y4MeYvxpg8rPdNgwLvmz9x6fuzyHi5/PXm2e0b2usOGTvz2PL/Df6N9Z5eaB/SffEKXosqhCajKsQY8wvWN/S37UXHsb75Ns7XLBTr2yFY3wwLrssBkrnyQxJTsQ5tTC1k3UHgjQIfpL7GmBki0hiYADwJBBljagIJWD2La2Ks8w9TsM8/AEewkuAFoQU2OYeVQC6on+/+MKxDQn2xDieG2cvzx5n/d3YcOA+0yfeaA4x1kr40sVypwv5eBZdd8vcWkepYh00PFbNNQTOAe8U6h1gNWHxxQ2PeN8Z0Adpg9fT+UOroC3cQqyeZ/33jb4y5pZTxFny9gvU7P4T1+29Y4HDvxb+BMSbNGPO8MaYpcBvwnIjEXuPrqdI0GVU97wE3ikhHY0wuMAt4Q0T87Q/+57AOoYH1wfKsiDQRqxz8TeALY0wOkALkYZ1LKo0vsA57zSpk3QTgMRHpap/ori4iA0TEH6iO9YGSAiAiD/Fb8rgiItJSRJ63z50hIo2wznGsspvMAp4SkRD7fFLBb7sbgaEi4ikiBc8p+WMd8jyBlbDeLC4W+1v4BOBdEalrx9Mw3/mOWVgn3FuLiC/w8tW85is0HXhIRDra5+veBFYbY/ZdwT7mYX3Av4b1XskDEJEo++/riZXUM4Dca4x3DXBGrCKManbvtK2UvlR/FjBARGLtuJ7H+huuAFZiffF6SkQ8RGQwEH1hQ7EKbiLsZHXGfi3X+nqqNE1GVYwxJgWrd3LhEM7vsD4c9mCdVJ+Odb4C++dnWJVze7E+QH5n7ycd65zAcvsQSUwJz3veGPOTMeZ8IevisIoHPsA6L5CIdS4IY8xW4D9YHw7JQDtg+VW8dLDOm3UFVotV0bYKq5f1vL1+Ala14SasAoT/Fdj+r0C4HeOrWL+rC6ZiHcY5BGzltwRXnBewXusq+9DeT1jn5TDGzMf64rDIbrOoFPv7QC69zmhdKba5yBjzM9ZrnIPVMwjnt0Nupd1HJtbvrS+X/n5qYP1+T2H9nk5g99DFuhB1/pU8j/1cuVi9ko5Y78/jwESsnmlptt8B3IdVxHPc3tdtxpgsY0wWMBjrfXgKq+Ai//uhGdbf6yzWe3OsMWbJlb4G9Ru59JCoUuoCEQnD+pDztHuDSikH0Z6RUkopp9NkpJRSyun0MJ1SSimnc2jPSKzhUzbb14jE2cteEWuww4327ZZ87V8SayiSHQWuolZKKeXCymPgwN7GmOMFlr1rjHk7/wJ7mI+hWNcgNAB+EpHmdsVMoWrXrm3CwsLKOl6llFIOsm7duuPGmDoFl1ekUWwHAjPt0tC9IpKIVddf5JhnYWFhxMXFlVd8SimlrpGIFDqaiKMLGAzWcBnrROSRfMufFGvU3k/yDVbZkEuH7kji0mFIlFJKuShHJ6NuxpjOWCNFPyEiPbAGxQzHulDtCNYFjVD48C6XVVeIyCMiEicicSkpKQ4KWymlVHlyaDIyxhy2fx4DvgKijTHJxppL5sJwKBeG2Eji0rG4QrDGjiq4z/HGmEhjTGSdOpcddlRKKVUJOeyckT3IopsxJs2+fxPwmogEG2OO2M3uwBqOBayh/KeLyDtYBQzNsMaeUkoph8rOziYpKYmMjIIDm6ur5ePjQ0hICJ6enqVq78gChnrAV/agtx7AdGPMAhH5TEQ6Yh2C24c1fw7GmC0iMgtrXK8c4IniKumUUqqsJCUl4e/vT1hYGFLovIzqShhjOHHiBElJSTRp0qRU2zgsGRlj9gAdCll+fzHbvIE1+KZSSpWbjIwMTURlSEQICgriSs7r63BASikFmojK2JX+Pqt0Mvp64yEOnkwvuaFSSimHqrLJ6ExGNq98s4U7xq5g08HTzg5HKVXFnT59mrFjx17xdrfccgunTxf/Gfa3v/2Nn3766WpDKxdVNhnV8PHky8euo5qXG/eMX8mChKPODkkpVYUVlYxyc4uv45o3bx41a9Ysts1rr71G3759ryk+R6uyyQggoq4/Xz3ejVbBNRgzbR0Tlu5BRzFXSjnDiy++yO7du+nYsSNRUVH07t2bYcOG0a5dOwAGDRpEly5daNOmDePHj7+4XVhYGMePH2ffvn20atWK0aNH06ZNG2666SbOn7cmVh4xYgSzZ8++2P7ll1+mc+fOtGvXju3btwOQkpLCjTfeSOfOnXn00Udp3Lgxx48XHFbUcSrS2HROUdvPmxmjY3h+1ibemLeN/SfP8cptbfBwr9J5Wqkq69Vvt7D18Jky3WfrBjV4+bY2xbb55z//SUJCAhs3bmTJkiUMGDCAhISEi6XRn3zyCbVq1eL8+fNERUVx5513EhQUdMk+du3axYwZM5gwYQJDhgxhzpw53HfffZc9V+3atVm/fj1jx47l7bffZuLEibz66qv06dOHl156iQULFlyS8MqDfuICPp7u/PfeTjzWM5zPVx1g1NQ4zmbqLNNKKeeJjo6+5Bqd999/nw4dOhATE8PBgwfZtWvXZds0adKEjh07AtClSxf27dtX6L4HDx58WZtly5YxdOhQAPr160dgYGCh2zpKle8ZXeDmJrzYvyWNg3z5y9wE7hq3gskPRREcUM3ZoSmlylFJPZjyUr169Yv3lyxZwk8//cTKlSvx9fWlV69ehY4W4e3tffG+u7v7xcN0RbVzd3cnJ8f64u3sUxTaMyrg3uhQJo+IIunUeQZ9uJyEQ6nODkkpVQX4+/uTlpZW6LrU1FQCAwPx9fVl+/btrFq1qsyf/4YbbmDWrFkALFy4kFOnTpX5cxRHk1EhejSvw5wx1+MuwpCPV/LztmRnh6SUcnFBQUF069aNtm3b8oc//OGSdf369SMnJ4f27dvz17/+lZiYmDJ//pdffpmFCxfSuXNn5s+fT3BwMP7+/mX+PEURZ3fNrkVkZKRx5OR6x85kMPLTOLYcTuVvt7ZmRLfSjbGklKpctm3bRqtWrZwdhlNlZmbi7u6Oh4cHK1euZMyYMWzcuPGa9lnY71VE1hljIgu21XNGxahbw4cvHo3h6ZkbeeXbrew/mc5fBrTG3U2HDVFKuZYDBw4wZMgQ8vLy8PLyYsKECeX6/FU7GS19G5r2hpAuRTbx9fLgo/u68Oa8bUxatpeDJ8/z/r0d8fWq2r86pZRradasGRs2bHDa81fdc0YZqbD+U5jcHzbOKLapu5vw11tb89rANizansyQj1eSfEbnPVFKqbJSdZORTwCMXgKNomHuY7DgJcgt/tqiB64LY+KDkexJOccdHy5n+9GyvTBOKaWqqqqbjACqB8H9X0HXx2DVWPh8MKSfLHaTPi3r8eVj15FrDHeNW8kvO0s/X4dSSqnCVe1kBODuCf3/BQM/hAMrYXwvSN5S7CZtGgQw94luNKrly8NT1jJt9f7yiVUppVyUJqMLOt0HD82HnEyYeCNs/brY5sEB1fjysevo0aw2f/4qgX/M20ZeXuUtk1dKVS5+fn4AHD58mLvuuqvQNr169aKky1/ee+890tN/m9etNFNSOIJDk5GI7BORzSKyUUTi7GW1RORHEdll/wy0l4uIvC8iiSISLyKdHRlboUIi4ZElUK81zHoAFr0BeXlFNvfz9mDCA5HcH9OYj5fu4Ynp68nILn64d6WUKksNGjS4OCL31SiYjEozJYUjlEfPqLcxpmO+i5xeBH42xjQDfrYfA/QHmtm3R4Bx5RDb5WoEw4jvrZ7S0rdg5jDIKLpQwcPdjdcGtuEvA1qxYMtRho5fRUpaZjkGrJRyBS+88MIl8xm98sorvPrqq8TGxl6c7uHrry8/YrNv3z7atm0LwPnz5xk6dCjt27fnnnvuuWRsujFjxhAZGUmbNm14+eWXAWvw1cOHD9O7d2969+4N/DYlBcA777xD27Ztadu2Le+9997F5ytqqopr4YyLZQYCvez7nwJLgBfs5VONNSTEKhGpKSLBxpgj5R6hhzfc/gHU7wALXoSJfWHodKgdUWhzEWFU96Y0quXL0zM3cMfY5UweEUWzeuU3lIZSqozMfxGObi7bfdZvB/3/WWyToUOH8swzz/D4448DMGvWLBYsWMCzzz5LjRo1OH78ODExMdx+++2IFH7h/bhx4/D19SU+Pp74+Hg6d/7tANMbb7xBrVq1yM3NJTY2lvj4eJ566ineeecdFi9eTO3atS/Z17p165g8eTKrV6/GGEPXrl3p2bMngYGBpZ6q4ko4umdkgIUisk5EHrGX1buQYOyfde3lDYGD+bZNspddQkQeEZE4EYlLSXFgJZsIdH0EHpgL51JgQh/YVfy0vTe3qc+sR68jIzuPweNWsDyx/CamUkpVbp06deLYsWMcPnyYTZs2ERgYSHBwMH/6059o3749ffv25dChQyQnFz1W5tKlSy8mhfbt29O+ffuL62bNmkXnzp3p1KkTW7ZsYevWrcXGs2zZMu644w6qV6+On58fgwcP5tdffwVKP1XFlXB0z6ibMeawiNQFfhSR7cW0LSzVX1YRYIwZD4wHa2y6sgmzGE16WOeRZg6HaXdB31eg29NWsipE+5CazH3ieh6espYHP1nDm4PbMSSykcPDVEqVkRJ6MI501113MXv2bI4ePcrQoUOZNm0aKSkprFu3Dk9PT8LCwgqdOiK/wnpNe/fu5e2332bt2rUEBgYyYsSIEvdT3LilpZ2q4ko4tGdkjDls/zwGfAVEA8kiEgxg/zxmN08C8n9qhwCHHRlfqQU2hpE/QJtB8NPLMGcUZKUX2Twk0JfZY67nuvAg/jg7nrd/2KGVdkqpEg0dOpSZM2cye/Zs7rrrLlJTU6lbty6enp4sXryY/fuLv4ykR48eTJs2DYCEhATi4+MBOHPmDNWrVycgIIDk5GTmz59/cZuipq7o0aMHc+fOJT09nXPnzvHVV1/RvXv3Mny1l3JYMhKR6iLif+E+cBOQAHwDPGg3exC4cEbuG+ABu6ouBkh1yvmionhVh7smQ+zfIGEOfHIznD5QZPMaPp58MiKKoVGN+GBxIk9/sVEr7ZRSxWrTpg1paWk0bNiQ4OBghg8fTlxcHJGRkUybNo2WLVsWu/2YMWM4e/Ys7du356233iI6OhqADh060KlTJ9q0acPDDz9Mt27dLm7zyCOP0L9//4sFDBd07tyZESNGEB0dTdeuXRk1ahSdOnUq+xdtc9gUEiLSFKs3BNbhwOnGmDdEJAiYBYQCB4C7jTEnxepbfgD0A9KBh4wxxRbIO3oKiSLt/MHqHbl7wpCpEHZDkU2NMXz0yx7+tWA7kY0DGf9AJLWqe5VjsEqpkugUEo5xJVNIOKxnZIzZY4zpYN/aGGPesJefMMbEGmOa2T9P2suNMeYJY0y4MaZdSYnIqZrfDKMXQbVaMHUgrJkARSR1EWFMr3A+HNaZ+EOp3DF2OXtSzpZzwEopVbHpCAxXq3YzGP0zhMfCvN/Dt09ZozcUYUD7YGaMjiEtI4fB41awes+JcgxWKaUqNk1G18InAO6dAd2fh/VTYcqtkHa0yOZdGgcy9/Fu1Kruxf2T1jB3w6FyDFYpVZzKPOt1RXSlv09NRtfKzd0qarh7CiQnWAOtJq0rsnlokC9fjelG58Y1eeaLjfzfT7v0n0ApJ/Px8eHEiRP6v1hGjDGcOHECHx+fUm/jsAKG8uC0AoaiHN1sDR+Ulgy3vQcdhxXZNCsnjxf/F8//1h9icOeG/HNwe7w89LuBUs6QnZ1NUlJSidfeqNLz8fEhJCQET0/PS5YXVcCgc2eXpfrtrAn7vnwQ5o6xktONfwf3y3/NXh5u/OfuDoQFVeedH3dy+PR5PrqvCzV9tdJOqfLm6elJkyZNnB1GlaZfxcvaFUzYJyI8FduM9+7pyPr9pxk8bgX7T5wr54CVUsr5NBk5whVO2DeoU0M+GxnNyXNZ3DF2BVsP63TmSqmqRZORI13BhH1dmwbxvzHXA/DOjzvKK0KllKoQNBk52mUT9r1e5IR9Tev4cW90IxZtP8ah09c+8KBSSlUWmozKwyUT9v272An7hkaFYoAv1hQ97p1SSrkaTUbl5cKEff3/DbsWWhP2HU+8rFmjWr70bF6HmWsPkp1b9JTnSinlSjQZlaeLE/Z9DenH7Qn7frys2fCujTmWlsnP24qeREsppVyJJiNnaNIdRi+GmqEw7W5Y9u4lA632blGH4AAfpq3WQ3VKqapBk5GzXDJh3yswZ+TFCfs83N0YGhXKr7uO63VHSqkqQZORM10yYd//4JObLk7Yd09UI9zdhOlayKCUqgI0GTmbiDXq97Av4NR+6wLZI5uoH+BDbMu6fBmXRGaOzhCrlHJtmowqigsT9ombdS0SMDymMSfPZbEgoehpKZRSyhU4PBmJiLuIbBCR7+zHU0Rkr4hstG8d7eUiIu+LSKKIxItIZ0fHVuHUbgaRI60Ku5N76R5Rm0a1qjFdCxmUUi6uPHpGTwPbCiz7gzGmo33baC/rDzSzb48A48ohtoqny4NW72jdZNzchGHRjVm99ySJx9KcHZlSSjmMQ5ORiIQAA4CJpWg+EJhqLKuAmiIS7Mj4KqQaDaDlAFj/GWRncHdkCJ7uomXeSimX5uie0XvAH4GCQwm8YR+Ke1dEvO1lDYGD+dok2cuqnqhRcP4kbJ1LbT9v+rUNZs66JM5naSGDUso1OSwZicitwDFjTME5uF8CWgJRQC3ghQubFLKby6ahFZFHRCROROJSUlLKMuSKo0kPCGoGayYAMCw6lDMZOXwXf9jJgSmllGM4smfUDbhdRPYBM4E+IvK5MeaIfSguE5gMRNvtk4BG+bYPAS779DXGjDfGRBpjIuvUqePA8J1IxOodHYqDwxuIaVqLpnWq6zVHSimX5bBkZIx5yRgTYowJA4YCi4wx9104DyQiAgwCEuxNvgEesKvqYoBUY8wRR8VX4XUYCp6+sHYSIsLwro3ZcOA0Ww6nOjsypZQqc864zmiaiGwGNgO1gdft5fOAPUAiMAF43AmxVRzVakK7u2HzbDh/ijs7N8Tbw03LvJVSLqlckpExZokx5lb7fh9jTDtjTFtjzH3GmLP2cmOMecIYE26vjyuP2Cq0qFGQcx42zqCmrxe3tm/A3A2HOJuZ4+zIlFKqTOkIDBVZcHsIiYa1EyEvj+ExoZzLyuXrjYecHZlSSpUpTUYVXdQoOLkb9v5Cp0Y1aVnfn+mrD2DMZYWGSilVaWkyquhaDwTfIFg70SpkiGnMlsNn2JSkhQxKKdehyaii8/SBzg/AjnmQeohBHRvg6+XOtFX7nR2ZUlckIzuXV7/dwg3/WsTxs5nODkdVMJqMKoMuD1kzwa6bgr+PJwM7NuTb+MOkpmc7OzKlSmXTwdMMeP9XJi/fR9Kp8/y6y0UvWFdXTZNRZRDY2JpiYv2nkJPF8K6hZGTn8b8NSc6OTKliZefm8c6POxk8bgXpWbl8NjKaQF9PlieecHZoqoLRZFRZRI2Cs8mw/TvaNgygQ0iAFjKoCm1Xchp3jF3O+z/vYmDHBix4pgfdm9Xh+vDaLE88ru9ddQlNRpVFeCzUbGyVeQPDuzZm17GzrN13ysmBKXWpvDzDxF/3MOC/yzh8OoOP7uvCO0M6ElDNE4BuEbU5kprB3uPnnBypqkg0GVUWbm4QNRL2L4fkrdzaIRh/Hw+mrdZCBlVxHDyZzr0TVvH699vo2bwOPzzTg35t61/SpltEEADLE487I0RVQWkyqkw63gfu3hA3CV8vD+7sHML8zUc5oZVJysmMMXyx9gD93lvK1sNn+Pdd7Rl/fxfq+Htf1ja0li8hgdVYpslI5aPJqDKpHgRtB8OmmZCZxrCuoWTl5jF7nRYyKOc5lpbByE/jeGHOZjo0qsmCZ3twd2QjrLGQLycidAuvzcrdJ8jN0/NGyqLJqLKJGgVZZyH+C5rX8yc6rBbT1xwgT/+plRPM23yEm99dyvLE47x8W2s+H9mVhjWrFd7YGGvg3zmj6NHElzMZOSQc0ou3lUWTUWXTsAsEd4C1k8AYhnUNZf+JdFbs1lJZVX5S07N5euYGHp+2ntBavnz/VHce6tYEN7fCe0OkHYWZw2HOSNj8Jd3dNgOwfLceqlMWTUaVzYWJ945thQMr6de2PoG+nlrIoMrN0p0p3PzeUr6PP8JzNzZnzpjriajrV3hjY2DjdPgwGnb/DDe+Bl7+1Ej6hZb1/bWIQV2kyagyansX+ATA2on4eLpzd2QjFm5NJvlMhrMjUy4sPSuHv8zdzAOfrMHfx4OvHu/GU7HN8HAv4mMk9RBMuxvmjoG6reGx5dDtaWjSA3b/zA3hQazdd4qM7NzyfSGqQtJkVBl5+VqVdVu/gbRk7o0OJTfPMGvtQWdHplzUuv0nueX/fmXa6gOM7t6Eb393A+1CAgpvbA9dxdgY61KE/m/BiHlQO8JaHxELpw/Qt14aWTl5rNuv18opTUaVV+TDkJcNG6bSpHZ1boiozYw1B7Q6SZWpzJxc3lqwnbs/WklOnmHG6Bj+PKA1Pp7uhW9waj98Ngi+fdo6tzlmBXR91LpO7oKIWAA6Za3Dw030UJ0CNBlVXrUjoGlviJsCuTkM7xrK4dQMftl5zNmRKRex7cgZBn6wnLFLdjMkshELnulBTNOgwhvn5cGaCTDuekiKgwHvwAPfQK0ml7cNDIOgCLz3LaZTaE1NRgooh2QkIu4iskFEvrMfNxGR1SKyS0S+EBEve7m3/TjRXh/m6NgqvahRcCYJdv1A39b1qOPvzbRVB5wdlarkcvMMY5ckcvsHyzh+NotJD0byzzvb4+ftUfgGJ/fAp7fBvN9DSBQ8vtIaLcStmI+X8FjYt4weTf3ZfChVR6BX5dIzehrYlu/xv4B3jTHNgFPASHv5SOCUMSYCeNdup4rTvB/UaAhrJuDp7sY9kY1YtOMYSafSnR2ZqqT2HT/HkI9X8taCHdzYuh4Ln+1BbKt6hTfOy4WVY2Hs9XB0M3m09cUAACAASURBVNz+Adz/FdQMLfmJIvpCznlu8ttDnoGVe/TShKrOoclIREKAAcBE+7EAfYDZdpNPgUH2/YH2Y+z1sVLUJdzK4u5hzXW0ZzEcT2RodCMAvtBCBnWFjDF8tmo//f/vV3Ylp/F/Qzvy4bDO1KruVfgGx3fB5P7ww0tWddwTq6Dz/dalB6UR1g3cvYg4s5rqXu56qE45vGf0HvBHIM9+HAScNsbk2I+TgIb2/YbAQQB7fard/hIi8oiIxIlIXEqKTtBF5wfAzQPiPiEk0JfeLeoyc+1BsnPzSt5WKeBoagYPTl7LX+cmEBkWyMJnezKwY8PCh/PJzYHl/wcf3QApO+COj2HYF1CjwZU9qVd1aHw97rsXEd2kll78qhyXjETkVuCYMWZd/sWFNDWlWPfbAmPGG2MijTGRderUKYNIKzn/etDqdtj4OWSlM7xrKClpmfy8LdnZkakKzhjD1xsPcdO7v7B270n+PqgtUx+Opn6AT+EbHNsGk26EH/9mHWZ7YjV0GFr63lBB4bGQso2bQnLYk3KOI6nnr/7FqErPkT2jbsDtIrIPmIl1eO49oKaIXDgTGgIctu8nAY0A7PUBwEkHxuc6okZBRiokzKFXi7o0CPBh2motZFBFO3kuiyenb+DpmRuJqOvH/Ke7c39M4yJ6Q9mw9N/wcQ84tQ/unAT3fA7+9S9veyUi+gLQ0yMBQGd/reIcloyMMS8ZY0KMMWHAUGCRMWY4sBi4y272IPC1ff8b+zH2+kVGp4IsncbXQ51WsHYC7gJDo0P5dddx9unkZaoQi7Ync/N7S1m49Sh/7NeCLx+7nrDa1QtvfHQzTOgDi16HlgPgiTXQ7q6r7w3lV7cV+Dcg+Ngyavt56XmjKs4Z1xm9ADwnIolY54Qm2csnAUH28ueAF50QW+UkYpXSHtkEh9ZzT1Qj3N2EGWu0d6R+czYzhxfnxPPwlDiCqnvx9RM38HivCNwLG9w0JwsW/wPG94K0IzDkM7h7CviV4aFxEYjog+xdQremNXUq8iquXJKRMWaJMeZW+/4eY0y0MSbCGHO3MSbTXp5hP46w1+8pj9hcRvt7wMsP1k6kXg0fbmxVjy/XJZGZo+N+KVi95wT93lvKrLiDjOkVztdPdqN1gxqFNz68wUpCv/wT2gy2ekOtb3dMYBF9ISOV24KOcCwtk8RjZx3zPKrC0xEYXIVPDetkcsIcSD/J8JhQTp7LYkHCUWdHppwoIzuX17/bytAJq3B3E7587Dpe6NcSb49ChvPJzoCfXoUJsXD+JNw7E+6cAL61HBdg014gbkTnbgB0KvKqTJORK4kcCbmZsOFzuoXXpnGQrxYyVGGJx85y23+XMXHZXoZ3DWXeU93p0riIxJIUZxUoLHsHOtwLj6+CFv0dH2S1QGgYSY1Dv9A4yJdlWsRQZWkyciX1WkPjbhA3CTcM90aHsmbvSXYlpzk7MlXOViQeZ/DY5ZxKz+LTh6N5fVA7qhc2nE/2efjhz1bJdtY5GD4HBn0I1WqWX7ARsXBoPX3DPFm95wQ5eo1claTJyNVEjbTKb3cv4u4uIXi6i/aOqphZcQd54JM11Kvhw1ePd6Nn8yKKDvavhHHdYOUH0PlBa0y5Zn3LN1iwS7wNA3y3k5aZQ7xORV4laTJyNS1vg+p1Ye0Egvy86d82mDnrkzifpYUMri4vz/DvH7bzx9nxXBcexJzHr6dRLd/LG2adg/kvWMP55GXDA1/Dbe9Z5x2doUEnqBZIm/NrEYHlu/S8UVWkycjVeHhBlwdh5w9waj/Du4aSlpHDt/GHS95WVVoZ2bk8NXMDHy7ezb3RjfhkRBQ1fDwvb7h3KYy9DlZ/BNGjYcxKq4jAmdzcoWlvvPctpnV9fx0aqIrSZOSKuoywruFYN5noJrWIqOvHdD1U57JOnM1k2IRVfBd/hJf6t+TNO9rhWXAq8Mw0+O5Za6oHcbNmXr3l3+Dt55ygC4qIhbPJDG54mvX7T2tPvgrSZOSKAkKgxS2wfiqSm8XwrqFsPHiaBD0W73ISj6UxaOxythw+w7jhnXm0Z/jlQ/ok/mz1huImQ8wT1uyrYd2cE3BRwq3ZX3t7bCYrN4+1+3QksKpGk5GrihoJ6Sdg69cM7hSCt4cb03VEBpdiVcyt4HxWLjMfiaF/u+BLG2Seha+fhM8Hg2c1GLkQ+r0JXoWcR3K2GsFQtw2NT63Ay91NrzeqgjQZuaomvaBWOKydSICvJ7d1aMDXGw5xNjOnxE1VxVewYq5TaOClDVIPweR+sHEadHsGHv0VGkU7J9jSiojF/eBqYkK89bxRFaTJyFW5uVm9o4Or4Ug8w7uGci4rl7kbDjk7MnUNSlUxd3iDNbjpyX0wbBbc+Cp4FjEtREUSEQt52dwdtJcth89w6lyWsyNS5ajYZCQiffLdb1Jg3WBHBaXKSMdh4FEN4ibRsVFNWgfXYNrqAzoYZSVVqoq5rd/AJ/3B3cs6LNfsRucEezVCrwNPX7rmbcToVORVTkk9o7fz3Z9TYN1fyjgWVdaqBUK7OyF+FpJ5huExoWw7coaNB087OzJ1hUqsmDMGlr0Ls+6Hem1g9M/WiByViYc3hHWnTvKv+Hl7sEzPG1UpJSUjKeJ+YY9VRRQ1GrLTYdNMBnZsSHUvdx2RoZJJPHaWO8auKLpiLicLvnkSfnrFGmV7xHfgV9dp8V6TiL7Iqb3c3iiDFZqMqpSSkpEp4n5hj1VF1KAjNIyEtRPx83JnYKeGfLvpMKnp2c6OTJXChTHm0rNyCq+YSz9pVctt+Bx6/NGahdWzmnOCLQsRVon3bX5b2XcinYMn050ckCovJSWjpiLyjYh8m+/+hcdNSthWVRRRo+D4Ttj3K8OiQ8nMyWPO+iRnR6VKUGLF3IndMLGvVaRyx8fQ589W4UplFhQOgWG0O78OgBVaVVdllPTOHQj8B+vc0YX7Fx4Pcmxoqsy0ucM6f7RmAm0bBtCxUU2mr9FChoqqVBVz+5bBxFg4fwoe+Maay8pVRPSl+uEVNPBzY7lOKVFlFJuMjDG/5L8BK4AzwDb7cZFExEdE1ojIJhHZIiKv2suniMheEdlo3zray0VE3heRRBGJF5HOZfQalacPdLoftn8PZw4zvGsoicfOsmavXuVe0ZSqYm7DNJg6CKrXsQoVGl/nnGAdJTwWyT7H8AZHWLFbpyKvKkoq7f5IRNrY9wOATcBUYIOI3FvCvjOBPsaYDkBHoJ+IxNjr/mCM6WjfNtrL+gPN7NsjwLirekWqcJEPgcmDdZ9ya/sG1PDx0EKGCqbEirm8PKtI4evHofH1MPJHqNXUafE6TJPu4OZJrOdmjp/NYofOx1UllHSYrrsxZot9/yFgpzGmHdAF+GNxGxrLhQntPe1bcV9xBgJT7e1WATVFJLiY9upK1GpqzRuzbgrV3PMY3DmE+QlHOH4209mRKUpRMZeVDl8+aJVvdxkB980p3wnwypO3P4TGEJ66GoBlOqVElVBSMsp/CfSNwFwAY8zR0uxcRNxFZCNwDPjRGLPaXvWGfSjuXRHxtpc1BA7m2zzJXqbKStQoOHsUtn/P8K6hZOcaZq/TQgZnK7FiLu0oTLkFtn0LN70Bt74H7oVMD+FKImLxPL6FqFoZrNit542qgpKS0WkRuVVEOgHdgAUAIuIBlFg/aozJNcZ0BEKAaBFpC7wEtASigFrAC3bzwq5buqwnJSKPiEiciMSlpKSUFILKr9mNEBAKayfSrJ4/0U1qMWPNAfLy9Ji8s5RYMXd0szW0T8pOGDodrn/Smh7E1dmjeN8blMjqPSfI1qnIXV5JyehR4ElgMvBMvh5RLPB9aZ/EGHMaWAL0M8YcsQ/FZdr7vTB6YxLQKN9mIcBlM8IZY8YbYyKNMZF16hQxnbIqnJu7de5o36+QsoPhXUPZfyJdB6V0gvwVczFNg5g9ppCKuR3zYdLN1ugKDy+Alrc4J1hnqN8O/OpxHRs5l5XLJh01xOWVVE230xjTzy40mJJv+Q/GmOeL21ZE6ohITft+NaAvsP3CeSCxDogPAhLsTb4BHrCr6mKAVGPMkat9YaoIne63xi1bO4l+betTq7oX01ZpIUN5KlgxN/mhKAKq5TvsZgys/BBm3Au1m8HoRRDc3nkBO4MIhPehXspK3CVPhwaqAjyKWyki7xe33hjzVDGrg4FPRcQdK+nNMsZ8JyKLRKQO1mG5jcBjdvt5wC1AIpCOVTChyppfHWg9CDbNwDv2b9wdGcLEX/eSfCaDejUqwcjOldyJs5mMnhrH+gOneal/Sx7p0fTSQoXcbJj3B1g3GVreCoPHg1d15wXsTBF9cds0g0F1j7EisTbP9HV2QMqRik1GWIkiAZiFdcis1AerjTHxQKdClvcppDnGupjgidLuX12D6NGweRZs/pJ7o4bw8S97+GLtQZ6KbebsyFxa4rGzPDxlLclnMhg3vPPlhQrnT8OXI2DPYmsOotiXK/+ICteiaW9AGOS/jYf2BHMuM4fq3iV9ZKnKqqR3ejAwHrgZuB+rPPsbY8ynxphPHR2ccpCQKOuY/NqJhAX50r1ZbWauOUCuFjI4TIkVcyf3wqSbrPN5t39gzUFUlRMRQPUgaNCJDpnryMkzepG2iyvpnNEJY8xHxpjewAigJrBFRO4vj+CUg4hYZd7JCXBwDcO7hnI4NYMlO445OzKXVGLF3IFV1tA+Z5Ph/rnQWf+9LoqIxf/4Rmp7pOtU5C6uVF+97KF5ngHuA+YD6xwZlCoH7e4G7xqwdgKxrepR199bR2QoY6WqmIufBZ/eBj4BMOpna/QB9ZuIvojJ4/66+7SIwcWVNBzQqyKyDngO+AWINMaMNMZsLZfolON4Vbdmgt0yF8/zJxga1YjFO46RdEqH7C8L+SvmhkYVUTG3+E3432gIibYSUe0I5wVcUTWMBO8AbvTazPajaTpiiAsrqWf0VyAA6AD8A1hvj5ywWUTiHR6dcqzIkZCXDRumck90KALMXHOwxM1U8fKPMfdi/5b8Y3CBMeayM2DOSPjlX9BxONz/FfjWcl7AFZm7BzTtSUTaGsDoaAwurKTSFJ2zyJXVaQ5NekDcZBp2e4beLeryRdxBnu7b7NIPT1VqJVbMnT0GM4dB0lqrWu6GZ6vGiArXIqIvXtu+oZPPUVYkHuf2Dg2cHZFygJIKGPYXdsMaLeGG8glROVTUKEg9CLsWMjwmlJS0TH7amuzsqCqlEivmkrfChFg4mgBDpkL35zQRlYY9++uwoF163siFlXTOqIaIvCQiH4jITfboCL8D9gBDyidE5VAtbgH/YFg7kZ7N69KwZjUtZLgKWw+f4cHJxVTM7frJKt3OzYSHvofWA50TaGUUEAJ1WtKNjSSdOs+BE3pe0xWVdCzmM6AFsBkYBSwE7gIGGmP0v8kVuHtaUxIk/oT76b3cG92IZYnH2Xv8nLMjq1Q+XJyIj4c7sx697vKKuTUTYPrdEBhmDe3TsItTYqzUwmOpf3oDPmRq78hFlZSMmhpjRhhjPgbuBSKBW/NNiKdcQecHQdwh7hOGRDbCw02YsUZ7R6W1J+Us8xKOcN91jQms7vXbitwcmPdHmPd7aHYTPDzf+pavrlxELG65mfT3260D+7qokpJR9oU7xphcYK8xRqdddDU1gqHVrbDhc+pWM9zYuh5fxh0kIzvX2ZFVCuOX7sHL3Y2Hu+Wr98k4AzOGwpqPIeYJa/oHb3/nBVnZNb4ePHy4o8Y2ViQe12lPXFBJyaiDiJyxb2lA+wv3ReRMeQSoyknUaDh/CrZ8xfCujTmVns0PW0o1h2KVdjQ1gznrkxgS2Yg6/vY8kacPwCc3w+5FMOAd6PemNX2Hunqe1SDsBjplredUejZbj+jHj6spqZrO3RhTw775G2M88t2vUV5BqnIQdgPUbgFrJ3J9eBBhQb46tUQpTPx1D3kGHunR1FqQFGdVzKUegvtmQ9RI5wboSsJj8T+7lxBJYYUeqnM5ejGJslwYr+7QOtyObGBY11DW7DvJzmQ9KluU0+lZTF9zgNvaB1tFCwn/gykDrG/xIxdCeKED1KurFWHNIXFXwA6WJerFr65Gk5H6TYd7wLM6rJ3EXV0a4eXuxnQt8y7Spyv2k56Vy2O9wmHfcpj9EAR3sCrm6rZ0dniup3YzCGjEzd4JrN17kswcPafpSjQZqd/4BED7IZAwm1pyllva1WfO+iTOZ+k/fUHpWTlMWbGX2JZ1aVnPHxb9HfzqW6NuV6/t7PBckwhExNLs3DqyszPZcECnInclmozUpaJGQk4GbJzOsK6NScvI4dv4w86OqsKZseYgp9Kzebx3uFWocGAl9Pg9ePmWvLG6euGxeOSco4vbLlbo9UYuRZORulT9dtAoBuImEdU4gGZ1/XREhgKycvKY+OseopvUoktoICx6HQJCofMDzg7N9TXtCeLO3TV36sWvLsZhyUhEfERkjYhsEpEtIvKqvbyJiKwWkV0i8oWIeNnLve3Hifb6MEfFpkoQNQpO7kH2LGF411A2HTxNwqFUZ0dVYczdeIgjqRmM6RUOO+bD4fXQ84/g4e3s0FyfTwA0iuYG2cSmpFTSMrJL3kZVCo7sGWUCfYwxHYCOQD8RiQH+BbxrjGkGnAIu1L6OBE4ZYyKAd+12yhla3w6+tWHtJO7oHIKftwf/9/MuZ0dVIeTmGT76ZTetg2vQq1kQLH4DajWFDvc6O7SqIyKW+ue2UzPvNKv36FTkrsJhychYztoPPe2bAfoAs+3lnwKD7PsD7cfY62NFdEhjp/Dwtg457ZxPQOZRxvQK58etyazeo+W0P249yp6Uc4zpFY5s/dqaur3XS9a8O6p82CXefbwSdGggF+LQc0Yi4i4iG4FjwI/AbuC0MSbHbpIENLTvNwQOAtjrU4GgQvb5iIjEiUhcSkqKI8Ov2iIfsmYjXTeFh7s1ITjAhzfnbavSw7AYYxi7ZDeNg3y5pU1dWPIPqNMS2t7p7NCqlvodwLc2A/22s1zPG7kMhyYjY0yuMaYjEAJEA60Ka2b/LKwXdNknnzFmvDEm0hgTWadOnbILVl2qZig07wfrP6WaWy7P39SCTUmpfLf5iLMjc5rliSeIT0rl0R7huG+ZDcd3Qu8/6VA/5c3NDcL70CV7PbuSz3DsTIazI1JloFyq6Ywxp4ElQAxQU0QuHNMIAS7UDScBjQDs9QGAHhB2pqhRcC4Ftn3DHZ0a0iq4Bm8t2F5lLzYc90sidf29ubOj3Suq3x5a3ubssKqmiFiqZZ+ijezTqchdhCOr6eqISE37fjWgL7ANWIw1JxLAg8DX9v1v7MfY6xcZY6ruMaGKILwPBDaBtZNwdxP+fEsrkk6dZ+qK/c6OrNxtOnia5YknGNW9Cd4JM+HUPuj9Z+tbuip/9lBLN/ts0RJvF+HI/6RgYLGIxANrgR+NMd8BLwDPiUgi1jmhSXb7SUCQvfw54EUHxqZKw83Nugj2wAo4msANzWrTs3kd/rtoF6fTs5wdXbkauySRGj4eDOtSH375NzSMhOY3OzusqsuvLtRvTz/vBFYkHke/t1Z+jqymizfGdDLGtDfGtDXGvGYv32OMiTbGRBhj7jbGZNrLM+zHEfb6PY6KTV2BjsPByw9+fhWM4U+3tOJsZg7/XZTo7MjKTeKxNH7YksyD14fhlzANziRBn79Yw9Mo54noS3jmNtJST+rMxC5AjzGo4vnWsk7S71oI276lRX1/7u7SiKkr97H/RNX4APjolz34eLoxIqou/Po2NL4BmvZydlgqIhY3k8P1bltYrueNKj1NRqpk0Y9CvXYw/wXITOO5m5rj4ebGWz/scHZkDnfo9HnmbjjE0KhQgrZ+BmeToc+ftVdUEYREY7z86V9tC8t36Xmjyk6TkSqZuwfc+i6kHYEl/6ReDR9G92jK9/FHWH/glLOjc6gJS62jxY/E1IVl71onzhtf7+SoFAAeXkiTHvRwi2fl7uPkVuFr4FyBJiNVOo2ioMuDsGocHE3g0R5Nqe3nzZvfb3PZk8cnz2Uxc+0BBnZsSINtU+D8Sej9F2eHpfKLiKVW9lGCMg+w5bCOn1iZaTJSpRf7MlQLhO+epbqnG8/d2Jy4/af4YUuysyNziCnL95KRnccTMbVgxX+hxS0Q0sXZYan8ImIB6Om2ieU6+2ulpslIlZ5vLbjp75C0BjZMZUhkCBF1/fjXgu1k5+Y5O7oydTYzhykr9nFT63o0TfwUMlOtQg5VsQSGQVAE/att1aGBKjlNRurKdLjXqib78WU8Mk7yp1tasvf4OZebnnzG6gOcycjhdzGB1qHJNndYcz2piic8lk65CWzad5SM7Ko5Oogr0GSkrowIDPgPZJ2FH/9G7xZ1ua5pEO/9tJMzLjK3TGZOLhOX7eH68CDa7ZsM2enWyNyqYoroi6fJpEPeNtbvd+2CGlemyUhdubot4frfwcZpyP4V/HlAK06lZzNuyW5nR1Ym/rf+EMlnMnmqqz+smQDthkCdFs4OSxUlrBvG3Zve7pt0aKBKTJORujo9/mhNtf39c7StV407OjVk0rK9HDp93tmRXZPcPMPHv+ymXcMAuiZNgdxs6PWCs8NSxfGqjjS+jpu8EvTi10pMk5G6Ol6+cMu/IWU7rPqQ399s9Rz+U8kvhJ2fcIR9J9J5Lroasm4KdLrPmslVVWwRfWmUe4DjSbtJPe8ah4urGk1G6uq16Actb4Vf3qIhKTzcrQlfbTxEwqHKeb2HMYaxi3fTtE51eiXbkw73+INzg1KlE26VeN/gFs8qnZG4UtJkpK5Nv39aP+e/wOO9w6lZzZM351XOC2F/2ZnC1iNn+H0XT2TD59BlBNRs5OywVGnUbYXxb0Afj3gt8a6kNBmpa1OzEfR6EXbMo8a+hTwd24wVu0+wZEflmxJ+3JLdBAf4cPOJT8HdE7o/7+yQVGmJIBF96O6WwMpdrnkRtqvTZKSuXczjULc1zH+BYZ1qExbky5vztpFTiS6EXbf/FKv3nuT5zuCe8CVEjwb/+s4OS12JiL74mnP4n4jnaKpORV7ZaDJS187dEwa8A6kH8Vr+b17s35Jdx87y5bokZ0dWauOWJFLT15NBp6eCpy90e8bZIakr1bQXRtzo6b5JD9VVQpqMVNlofJ1VebbyQ26uc5LIxoH8Z+FOzmXmODuyEu04msZP247x+/ZZeGybCzFjoHptZ4elrlS1QGgYSazHZk1GlZDDkpGINBKRxSKyTUS2iMjT9vJXROSQiGy0b7fk2+YlEUkUkR0ionM6VzZ9XwNvf+T75/nTLS04fjaT8Usr/oS9H/2yG18vd4ac/Qy8A+C6J5wdkrpKEhFLa3azedeeSllEU5U5smeUAzxvjGkFxABPiEhre927xpiO9m0egL1uKNAG6AeMFRF3B8anylr1ILjxNTiwks4n5zOgXTDjl+4h+UzFPX5/8GQ632w6zPOt0/BKXGCNLFEt0NlhqasV0Rc3DC3T17E75ayzo1FXwGHJyBhzxBiz3r6fBmwDGhazyUBgpjEm0xizF0gEoh0Vn3KQjvdBoxhY+Fde7FmHnLw83v1xp7OjKtL4pXtwExh+fhpUqwUxjzk7JHUtGnQi1yeQnu7xLNPZXyuVcjlnJCJhQCdgtb3oSRGJF5FPROTC19CGwMF8myVRSPISkUdEJE5E4lJSKl/5sMtzc4Nb34GMVBqtf4v7Y8KYFXeQHUfTnB3ZZVLSMpkVd5Dnmp/AZ/9iuOFZ8PZ3dljqWri54x7em97uet6osnF4MhIRP2AO8Iwx5gwwDggHOgJHgP9caFrI5pcd9DXGjDfGRBpjIuvUqeOgqNU1qdcGrnsc1k/lmeYnqO7twT/mb3N2VJeZvHwvWbm5jMj8HPzqQdQoZ4ekykJELEGc4uSe9ZXq8oKqzqHJSEQ8sRLRNGPM/wCMMcnGmFxjTB4wgd8OxSUB+S93DwEOOzI+5UA9X4QaIdT4+QWe6tWYJTtSKtRhkzMZ2Xy2cj/PND1MtcOrrAtcvXydHZYqC/bQQFE569lcSYemqoocWU0nwCRgmzHmnXzLg/M1uwNIsO9/AwwVEW8RaQI0A9Y4Kj7lYN5+0P9fcGwLI9x/oGHNarw5bxt5eRWjwmnaqgOkZWYzOns61Aixhv5RrqFGMDl12tDDTYcGqkwc2TPqBtwP9ClQxv2WiGwWkXigN/AsgDFmCzAL2AosAJ4wxui0jZVZywHQvB+eS//F33rUYOuRM3y14ZCzoyIjO5dJy/byZMgefI9tgJ5/AA9vZ4elypBHs1ii3HcSt7PyXHhd1Tmymm6ZMUaMMe3zl3EbY+43xrSzl99ujDmSb5s3jDHhxpgWxpj5jopNlRMR6P8WmDxuOvAu7UMCeHvhDqdPDf3luiROnD3PY3kzITAMOg53ajzKASL64kkO3knLOZ+l32krAx2BQTlWYGPo+Qdk+3e81f4IR1IzmLRsr9PCycnNY/zS3TxWdyt+J7dY57bcPZ0Wj3KQ0Bhy3avRjY3E7T/p7GhUKWgyUo533e+gdgtarn+NW1oEMG7Jbo6fzXRKKN9vPsKhk+d4gllQuzm0H+KUOJSDeXhDkx7W9UZ63qhS0GSkHM/Dy7r26PQBXg9awPnsXN7/eVe5h2GMYdyS3YwOXI/fmUTo9RK46SAfrsq9WV8aSzJ7dsQ7OxRVCpqMVPkIuwE63EutjR/xVPtcpq0+UO7DtSzafoxdR0/zO7fZUK8ttB5Urs+vylmEVeIdnLKCU+eynByMKokmI1V+bvw7eFVnzLlx+HgI/5q/vVyfftyS3Yz0W4XfuQPQ+8/WaBHKdQWFk+kfSg+3TazUqcgrPP1vVOXHrw70fRmvg8t5r9UOFm5NZs3e8jm5vGbvSeL3H+Mpj/9Bg87Qon+5PK9yLo8WN3K921ZW7fz/9u48uqry3OP49zkncwIkZICQMMVQDYhGIAIiIDiheOXW6mpZSh3qdOvY2turkARQlQAAEZ5JREFU1mVb17Jzrbe1Wq22tcqytcpFpSiTzCAkMokEkCkDRJJAEkjIeM5z/zg7FDBIKDnZ53Cez1p7kbzZe/PLXoQn+93vfl97fz7UWTEy3WvEbZBdwBVlv2NIjzaenlvcLVP9P79kB3fELyepqQIm/yAw7Nyc9by5V5AgzRz+bIXbUcwpWDEy3cvjganPII0H+UPme2wsq2XOpopTH3cGtuw7xOpte3kgejYMGHt0uhgTAQaPxydRnFtfSHnNEbfTmC9hxch0v8wLYPS95JS+xbS0ffz8g600twXvxcQXlu7kjtgPSWyphslP2F1RJIntQXNmARM9G1m1w54bhTIrRsYdkx5HevTl6ehXqKip57XVJUH5a/ZUN7B40y7uj34Pci4LjOozESU+72ryPKV8srV7B8yY02PFyLgjtgdM+RlJNcX8uO8qfrvoM2qPdP3w25eW7+L2qPkkttXApCe6/Pwm9IkzxNu7e7EtRR7CrBgZ9wydBrlXML3hryQ0V/Lchzu69PSVh5qYV7SNb8fMgSFXQ/+CLj2/CRN9h9MYm8bI1o/Zvt+WIg9VVoyMe0Tg2l/iVR8vpr/Nq6v3UHqg6x4yv7JiN7fKP4n31cOkx7vsvCbMiODPmcylns2s/Gy/22nMSVgxMu7qnQPjH+HCQ4uZ6NnEL+Z1Tb9+3ZFW3vtoM3fFfAB510O//C45rwlPiUOvJkXq2bdlldtRzElYMTLuG/cQpObyq8TXWLCphPWlNWd8ytc+2sMM/zvE+RvtrshAziT8CMl7l9FqS5GHJCtGxn1RsTD1GZKbyvle/Bx+coYvwja2+HhnxXruiJ6PDL8RMvK6MKwJS4mpHEo5n7FsYGNZrdtpTAesGJnQkDMRht/EHbxDdckW5m/59/v2/15YyvSWt4mhLbBekTFA3HlXkS87KNrq3npa5uSsGJnQcdXTeGLi+VXCq/xsbvG/1Z3S6vMze1khM6IWIvnTIS03CEFNOIrLuwqvKEe2LnQ7iulA0IqRiPQXkcUiUiwin4rIQ057bxFZICKfOX+mOO0iIr8VkR0isklERgQrmwlRPfoglz/JSN8mhtcs5I21pad9inc37OPGhr/h9QhM+H4QQpqwlTWKJm8S2QdX09Dc5nYac4Jg3hm1AY+oah4wBrhPRIYCjwKLVHUIsMj5HOAaYIiz3Q28EMRsJlSNugPtdxFPxc3k5QUbONTU2ulD/X7l/xav5BtRS5ARtwaWPDemnTeK+n7jGC8bWbvbpgYKNUErRqpaoarrnI8PA8VAFjANeNXZ7VWgfYWzacBfNeAjIFlEMoOVz4Qojxe57jf00jq+1fI6f1iys9OHLizez7Ta1xGPF5nwSBBDmnDVa/g1ZMpBtm8udDuKOUG3PDMSkUHARcAaoI+qVkCgYAEZzm5ZQNkxh5U7bSee624RKRKRoqqqqmDGNm7pdxFScCczohayZsVC9tU2nvIQVWX2wqXcELUCKbgTevbrhqAm3ESfeyUAnp2LXE5iThT0YiQiScDbwMOqeujLdu2g7Qvje1X1JVUdpaqj0tPTuyqmCTWTn0AT0vmR9xV+PW/LKXdfvesAU6r/jHpj8Iz/bjcENGGpVzYHE3I4t76QA/XNbqcxxwhqMRKRaAKFaKaqznKa97d3vzl/Vjrt5UD/Yw7PBmx5xkgV1wvvNT9luOwicdNf2by37kt3f2/+Qq7zfgSj/yuwoqwxJ9E2eBKjPcWs2VZ26p1NtwnmaDoBXgGKVfWZY770LnCr8/GtwDvHtH/TGVU3Bqhr784zEer8r9E6cCL/Hf13Xpiz4qQvwn5SXsfEfS/T6k0k6tIHuzmkCTep+VOJlTb2b7KuulASzDujccAMYLKIbHC2a4GfAVeKyGfAlc7nAHOBXcAO4I/At4OYzYQDEaL/4xkSpI2ryp9jyfaOnxHOmTeXKd5CGPttSOjdzSFNuPEOuoQWiSFp71K3o5hjRAXrxKq6go6fAwF8Yd1nDfzae1+w8pgwlZYLl36Hact/wf+8+wbjv/sAUd5//Q61s6qeMXteoDG2J/GX3u9iUBM2ouOp7F3AiKp1lB44woDUBLcTGWwGBhMGvBMeoSFxAPccfp5Za48f6j3v/XeY5N2If+yDENfLpYQm3MSedxXneCrY8MkGt6MYhxUjE/qi40j46rPkeD6nZsEvj749X1HXSP6O31MflULieOvVNZ2Xln8NAA1b5rucJHwcaW5ly7bgLd1uxciEBcm9nIODpnKbbxZvzg/09S/85z+4xPMprWMfhphElxOacCJpX+FgdF/6VK7E77elyE+mqdXH8o9WM/e3D1D1k/Pp/ca1tLYFZyqloD0zMqar9b7h1zQ+O4Lcoh+zvaCAYdt+R210OikT7nU7mgk3ItRmjqegZA7F+w4wLDvN7UQho9Xnp3DzVipXzST38/cZLzvxI+zuMQLf8JvI0OCsB2XFyISPnpkcGfco45c/yawXb+cG2c7+S34K0XFuJzNhKOXCa+lR+g92fbyYYdk3uR3HVT6/sm57CSUr3ySr7D1G6yd4RSmPH8LOvEcZOGEG56RkBzWDFSMTVlIvu4+Kote5oXEhVVF96TPhTrcjmTCVMuxyfO95YOdCIPKKkaqycU8lW1fMJnX3bMb7CimQVqqjMynJvYfsibeS3Xdot+WxYmTCizeKxK/9jsaZX6XlsicgKsbtRCZcxfWiLHE4OXVraGnzExN19j9CV1WK99WxfuX7JG6bxcS2VeRLPYc9vajIuZHM8d8kbfBY0uRkb+UEjxUjE3Z65o6BH+whKyrW7SgmzLUOnsSwzc/y8bbtjBx2nttxgmZnVT2rVi3D++lbTGheys1STbPEsT97MrFjb6FH3lX08Ea7mtGKkQlPVohMF+g78jrY/CyVGz6As6wYlR08wuK162nb+CZjGz5khqcUHx72p4+l/uKnSLpwGgNik9yOeZQVI2NMxOoxcCS10ouEsiXAw27HOWOVh5pYsG4bdR+/xYi6BdwiW/GIUplyAYdG3EPPkV+nX4hOJGzFyBgTuTwe9qWOJb9qGS8+dTdNidn4ew0gJm0wPfsMILt3Iv1T4slKTiA+xut22g4dbGhh/sYSKgpnM7T6A270bCBW2qhNHMjhC75Hr4unk5F6jtsxT8mKkTEmomVNvgvP7PXc1fImnsMKh4FyaFEvezWNMs1graZzMLovTUnZ+JMHEps2iOS0LLJ7J5CdkkBWSjxJsd333+mhplYWbN7HjrXvk1Mxl2s9a+kpjTTEpdKYdxuxo28mud9F4MJAhH+XnGxa/nAwatQoLSoqcjuGMeZs0NYMtWVQW4K/poTGyp00V+9BakuIrS8nobXmuN2PaCzlmka5plOm6VRHZ9KUmIUmDyA2LYfU1IzjilWv+DMbINDY4mNR8edsKFxKv9I5XCur6Cs1NHsSOJI7leTRNyODJ4AnNO/g2onIx6o66sR2uzMyxhgIDIpJy4W0XDxAorMd1dIAtaVQU4LWlkDlLjKqd9OntpRxDR8R23YY6gls5XBI4ynXDMo0ndWaTmVUH5oS+0PyAGLTBpORlkq20wWYnRJPckI0csKdTHObj2Xbq1lVWETyztlMZQXXefbh80ZxuP8k9OKbiT13CrHR8d12mYLFipExxnRGTCJk5EFGHgIkONtRjbWBYlVbgtbsIaZ6D9lVu+lfV0pc/Wai/U3QQGDbCwe0B2WaTomms1Iz2O/pQ3NSFqQMIjZ1IP7memK2zWaKfzk/9HwGHjiUcTH+gu/jHTaN5LNs7S4rRsYY0xXikwNb5gUIEOdsAKjCkQNQUwK1e9CaUpKqd3NO9W6G1JUS17AOr7bCEQLbXvCp4BWlPuVcfCN/iPeCm+iZ3N+t7y7orBgZY0ywiUBiWmDLHokAsc4GgN8P9Z8f7QaktgSPvw2GTiOpzzD3cnejoBUjEfkTcB1QqarnO20/Au4C2tePflxV5zpfewz4FuADHlTVecHKZowxIcXjgZ79AtuAMcDJl8k+WwVzMqa/AFM6aP+NquY7W3shGgp8AxjmHPO8iIT2kBBjjDFdJmjFSFWXAQc7ufs04G+q2qyqu4EdwMXBymaMMSa0uDFN7f0isklE/iQiKU5bFlB2zD7lTtsXiMjdIlIkIkVVVVUd7WKMMSbMdHcxegE4B8gHKoBfO+0ddY92+Dauqr6kqqNUdVR6emjOsWSMMeb0dGsxUtX9qupTVT/wR/7VFVcOHDtmMRvY153ZjDHGuKdbi5GIZB7z6VeBzc7H7wLfEJFYERkMDAHWdmc2Y4wx7gnm0O43gMuANBEpB34IXCYi+QS64PYA9wCo6qci8iawBWgD7lNVX7CyGWOMCS02Uaoxxphuc7KJUsO6GIlIFVByhqdJA6q7IM7Zzq5T59h1OjW7Rp1ztl6ngar6hdFnYV2MuoKIFHVUpc3x7Dp1jl2nU7Nr1DmRdp3ceM/IGGOMOY4VI2OMMa6zYgQvuR0gTNh16hy7Tqdm16hzIuo6RfwzI2OMMe6zOyNjjDGus2JkjDHGdRFbjERkiohsE5EdIvKo23lCkYj0F5HFIlIsIp+KyENuZwplIuIVkfUiMsftLKFKRJJF5C0R2er8uxrrdqZQJCLfcX7mNovIGyISd+qjwltEFiNn4b7fA9cAQ4HpzgJ/5nhtwCOqmgeMAe6z6/SlHgKK3Q4R4v4X+EBVzwMuxK7XF4hIFvAgMMpZJdtLYPHRs1pEFiMCs4XvUNVdqtoC/I3AAn/mGKpaoarrnI8PE/iPo8N1piKdiGQDU4GX3c4SqkSkJzABeAVAVVtUtdbdVCErCogXkSgggQhYxSBSi1GnF/MzASIyCLgIWONukpD1LPB9wO92kBCWA1QBf3a6M18WkUS3Q4UaVd0L/AooJbDuW52qznc3VfBFajHq9GJ+BkQkCXgbeFhVD7mdJ9SIyHVApap+7HaWEBcFjABeUNWLgAbAnteewFkBexowGOgHJIrILe6mCr5ILUa2mF8niUg0gUI0U1VnuZ0nRI0DrheRPQS6fCeLyOvuRgpJ5UC5qrbfXb9FoDiZ410B7FbVKlVtBWYBl7icKegitRgVAkNEZLCIxBB4OPiuy5lCjogIgf79YlV9xu08oUpVH1PVbFUdRODf0oeqetb/Jnu6VPVzoExEznWaLiewhpk5XikwRkQSnJ/By4mAgR5BW1wvlKlqm4jcD8wjMFLlT6r6qcuxQtE4YAbwiYhscNoeV9W5LmYy4e0BYKbzS+Au4HaX84QcVV0jIm8B6wiMaF1PBEwNZNMBGWOMcV2kdtMZY4wJIVaMjDHGuM6KkTHGGNdZMTLGGOM6K0bGGGNcZ8XImC4mIj4R2eDMuPwPEUk4zeNfPp0JaUXkNhF57vSTGhM6rBgZ0/UaVTXfmXG5Bbi3sweKiFdV71RVexnURBQrRsYE13IgF0BEbhGRtc5d04vOUiaISL2IPCUia4CxIrJEREY5X5suIp84d1k/bz+piNwuIttFZCmBl5Pb229y9t0oIsu69Ts15gxYMTImSJzp/68hMINFHvB1YJyq5gM+4GZn10Rgs6qOVtUVxxzfD/g5MBnIBwpE5D9FJBP4MYEidCWBNbnaPQlcraoXAtcH9Rs0pgtF5HRAxgRZ/DHTJy0nML/f3cBIoDAw3RjxQKWzj4/AZLQnKgCWqGoVgIjMJLAeECe0/x34itO+EviLiLxJYIJNY8KCFSNjul6jc/dzlDPh5auq+lgH+zepqq+D9o6WOmnX4TxeqnqviIwmsNDfBhHJV9UDnQ1ujFusm86Y7rEIuFFEMgBEpLeIDDzFMWuAiSKS5jxfmg4sddovE5FUZ4mPm9oPEJFzVHWNqj4JVHP8UinGhCy7MzKmG6jqFhF5ApgvIh6gFbgPKPmSYypE5DFgMYG7pLmq+g6AiPwIWE1gJdB1BGafB/iliAxx9l8EbAzOd2RM17JZu40xxrjOuumMMca4zoqRMcYY11kxMsYY4zorRsYYY1xnxcgYY4zrrBgZY4xxnRUjY4wxrvt/lnKc5o1Uq0AAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "dnn_regressor = train_nn_regression_model(\n",
    "    learning_rate=0.1,\n",
    "    steps=700,\n",
    "    batch_size=10,\n",
    "    hidden_units=[20, 12, 6, 2],\n",
    "    training_examples=training_examples,\n",
    "    training_targets=training_targets,\n",
    "    validation_examples=validation_examples,\n",
    "    validation_targets=validation_targets)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "california_housing_test_data = pd.read_csv(\"https://download.mlcc.google.com/mledu-datasets/california_housing_test.csv\", sep=\",\")\n",
    "\n",
    "# Choose the last 5000 (out of 17000) examples for validation.\n",
    "test_examples = preprocess_features(california_housing_test_data)\n",
    "test_targets = preprocess_targets(california_housing_test_data)\n",
    "\n",
    "display.display(test_examples.describe())\n",
    "display.display(test_targets.describe())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
